2016-08-23 21:38:25,426 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.26
2016-08-23 21:38:25,431 : DEBUG : Machine : Command line arguments: {'force_platform': None, 'bcp': False, 'no_load_cache': False, 'configfile': ['config'], 'pause': False, 'mpfconfigfile': '/usr/local/lib/python3.4/dist-packages/mpf/mpfconfig.yaml', 'create_config_cache': True, 'loglevel': 10, 'logfile': 'logs/2016-08-23-21-38-25-mpf-kivypie.log', 'consoleloglevel': 20}
2016-08-23 21:38:25,431 : DEBUG : Machine : MPF path: /usr/local/lib/python3.4/dist-packages/mpf
2016-08-23 21:38:25,431 : INFO : Machine : Machine path: /home/sysop/robotech
2016-08-23 21:38:25,435 : DEBUG : Machine : Command line arguments: {'force_platform': None, 'bcp': False, 'no_load_cache': False, 'configfile': ['config'], 'pause': False, 'mpfconfigfile': '/usr/local/lib/python3.4/dist-packages/mpf/mpfconfig.yaml', 'create_config_cache': True, 'loglevel': 10, 'logfile': 'logs/2016-08-23-21-38-25-mpf-kivypie.log', 'consoleloglevel': 20}
2016-08-23 21:38:25,435 : DEBUG : Machine : Python version: 3.4.2
2016-08-23 21:38:25,435 : DEBUG : Machine : Platform: linux
2016-08-23 21:38:25,436 : DEBUG : Machine : Python executable location: /usr/bin/python3
2016-08-23 21:38:25,436 : DEBUG : Machine : 32-bit Python? True
2016-08-23 21:38:25,437 : DEBUG : Machine : Machine path: /home/sysop/robotech
2016-08-23 21:38:26,915 : INFO : Machine : Loading config from original files
2016-08-23 21:38:26,923 : DEBUG : YAML File Interface : Loading file: /usr/local/lib/python3.4/dist-packages/mpf/mpfconfig.yaml
2016-08-23 21:38:27,253 : INFO : Machine : Machine config file #1: /home/sysop/robotech/config/config
2016-08-23 21:38:27,257 : DEBUG : YAML File Interface : Loading file: /home/sysop/robotech/config/config.yaml
2016-08-23 21:38:27,627 : DEBUG : YAML File Interface : Loading file: /home/sysop/robotech/config/leds.yaml
2016-08-23 21:38:27,934 : DEBUG : YAML File Interface : Loading file: /home/sysop/robotech/config/shots.yaml
2016-08-23 21:38:27,986 : DEBUG : YAML File Interface : Loading file: /home/sysop/robotech/config/lightscripts.yaml
2016-08-23 21:38:28,012 : ERROR : root : Found a "quick_flash:" section in config file /home/sysop/robotech/config/lightscripts.yaml, but that section is not valid in machine config files.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/config_processor.py", line 65, in load_config_file
    '__valid_in__']:
KeyError: 'quick_flash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 100, in __init__
    self._load_config()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 286, in _load_config
    self._load_config_from_files()
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/machine.py", line 305, in _load_config_from_files
    config_type='machine'))
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/config_processor.py", line 82, in load_config_file
    full_file, config_type))
  File "/usr/local/lib/python3.4/dist-packages/mpf/core/config_processor.py", line 72, in load_config_file
    'files.'.format(k, filename, config_type))
ValueError: Found a "quick_flash:" section in config file /home/sysop/robotech/config/lightscripts.yaml, but that section is not valid in machine config files.
